package edu.kit.scc.webreg.dools.unicluster

import edu.kit.scc.webreg.entity.UserEntity;
import edu.kit.scc.webreg.entity.RegistryEntity;
import edu.kit.scc.webreg.drools.UnauthorizedUser;

import java.util.Date;

global org.slf4j.Logger logger;

rule "Registry old"

	when
		$date : Date()
		$registry : RegistryEntity( ($date.getTime() - agreedTime.getTime()) > 30*24*60*1000 )
	then 
		logger.info( "Date is more than 30d before now" );
		
end